version: '3.8'

services:
  rasa:
    image: rasa/rasa:latest-full
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    command: rasa run --enable-api --cors "*"

  action-server:
    image: rasa/rasa-sdk:latest
    ports:
      - "5055:5055"
    volumes:
      - .:/app
    command: rasa-sdk
